// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect, useCallback, useRef, useMemo } from "react";

// ─── DESIGN TOKENS ───────────────────────────────────────────────────────────
const T = {
  bg0:"#080A0F", bg1:"#0D1117", bg2:"#161B26", bg3:"#1E2638", bg4:"#252D3D",
  border:"rgba(99,120,170,0.15)", borderHover:"rgba(99,120,170,0.35)",
  blue:"#3B82F6", blueDim:"#1D4ED8", blueGlow:"rgba(59,130,246,0.18)",
  emerald:"#10B981", emeraldGlow:"rgba(16,185,129,0.15)",
  amber:"#F59E0B", amberGlow:"rgba(245,158,11,0.15)",
  crimson:"#EF4444", crimsonGlow:"rgba(239,68,68,0.15)",
  violet:"#8B5CF6", violetGlow:"rgba(139,92,246,0.15)",
  cyan:"#06B6D4",
  text0:"#F8FAFC", text1:"#CBD5E1", text2:"#94A3B8", text3:"#64748B",
  glass:"rgba(255,255,255,0.03)", glassBorder:"rgba(255,255,255,0.07)",
};

// ─── SAMPLE DATA ─────────────────────────────────────────────────────────────
const PROJECTS = [
  { id:1, client:"Meridian Energy Corp",    engagement:"SUT Reverse Audit FY2023",       type:"Reverse Audit",       tax:"Sales & Use Tax", states:["TX","LA","OK","NM"],       exposure:2840000, refund:1120000, risk:"High",     priority:"Critical", status:"In Progress",        health:72, manager:"Sarah Chen",  partner:"Robert Mills", due:"2024-03-15", tasks:24, open:9,  billingType:"Fixed Fee",   period:"2020-2023" },
  { id:2, client:"StellarNet Logistics",    engagement:"Multi-State Nexus Study",         type:"Nexus Study",         tax:"Sales & Use Tax", states:["CA","WA","OR","NV","AZ"], exposure:4200000, refund:0,       risk:"Critical", priority:"Critical", status:"Review Phase",       health:88, manager:"James Park",  partner:"Diana Foster", due:"2024-02-28", tasks:18, open:3,  billingType:"Hourly",      period:"2021-2024" },
  { id:3, client:"Ozark Resources LLC",     engagement:"Severance Tax Refund 2019-2022",  type:"Refund Review",       tax:"Severance Tax",   states:["AR","OK","TX"],           exposure:890000,  refund:670000,  risk:"Medium",   priority:"High",     status:"Waiting for Client", health:45, manager:"Laura Kim",   partner:"Robert Mills", due:"2024-04-10", tasks:15, open:11, billingType:"Contingency", period:"2019-2022" },
  { id:4, client:"BlueRidge Manufacturing", engagement:"TX Audit Defense 2021",           type:"Audit Defense",       tax:"Sales & Use Tax", states:["TX"],                     exposure:3100000, refund:0,       risk:"Critical", priority:"Critical", status:"Escalated",          health:31, manager:"Sarah Chen",  partner:"Diana Foster", due:"2024-02-10", tasks:32, open:18, billingType:"Fixed Fee",   period:"2021"      },
  { id:5, client:"Pinnacle Retail Group",   engagement:"Taxability Research — SaaS",      type:"Taxability Research", tax:"Sales & Use Tax", states:["NY","NJ","CT","MA","PA"], exposure:560000,  refund:0,       risk:"Low",      priority:"Medium",   status:"Planning",           health:95, manager:"James Park",  partner:"Robert Mills", due:"2024-05-20", tasks:12, open:10, billingType:"Hourly",      period:"2023-2024" },
  { id:6, client:"Cascade Oil & Gas",       engagement:"Severance Audit Defense WY",      type:"Audit Defense",       tax:"Severance Tax",   states:["WY","ND"],                exposure:7800000, refund:0,       risk:"Critical", priority:"Critical", status:"In Progress",        health:58, manager:"Laura Kim",   partner:"Diana Foster", due:"2024-03-01", tasks:40, open:14, billingType:"Fixed Fee",   period:"2018-2022" },
];

const TASKS = [
  { id:1, title:"Prepare TX Audit IDR Response — Batch 3",       project:"BlueRidge Manufacturing", priority:"Critical", status:"In Progress",        due:"2024-02-08", assignee:"Alex Torres", hours:8,  estimate:12 },
  { id:2, title:"Review Nexus Footprint — CA Economic Nexus",     project:"StellarNet Logistics",    priority:"High",     status:"Review Phase",       due:"2024-02-12", assignee:"Priya Nair",  hours:5,  estimate:6  },
  { id:3, title:"Compile Refund Schedules — AR Severance 2019",   project:"Ozark Resources LLC",     priority:"High",     status:"Waiting for Client", due:"2024-02-20", assignee:"Marcus Lee",  hours:3,  estimate:10 },
  { id:4, title:"SaaS Taxability Matrix — 5-State Analysis",      project:"Pinnacle Retail Group",   priority:"Medium",   status:"Planning",           due:"2024-03-05", assignee:"Priya Nair",  hours:0,  estimate:16 },
  { id:5, title:"WY Audit — Computational Errors Expert Review",  project:"Cascade Oil & Gas",       priority:"Critical", status:"In Progress",        due:"2024-02-15", assignee:"Alex Torres", hours:14, estimate:20 },
  { id:6, title:"Meridian — Overpayment Schedule Finalization",   project:"Meridian Energy Corp",    priority:"High",     status:"In Progress",        due:"2024-02-25", assignee:"Marcus Lee",  hours:6,  estimate:8  },
];

const TEAM = [
  { id:1, name:"Sarah Chen",  role:"Manager",        avatar:"SC", color:T.blue,    projects:3, utilization:92, expertise:["TX","LA","OK"], status:"active"  },
  { id:2, name:"James Park",  role:"Senior Manager", avatar:"JP", color:T.violet,  projects:2, utilization:78, expertise:["CA","WA","NY"], status:"active"  },
  { id:3, name:"Laura Kim",   role:"Manager",        avatar:"LK", color:T.emerald, projects:2, utilization:88, expertise:["AR","WY","ND"], status:"active"  },
  { id:4, name:"Alex Torres", role:"Senior",         avatar:"AT", color:T.cyan,    projects:4, utilization:97, expertise:["TX","NY","CA"], status:"at-risk" },
  { id:5, name:"Priya Nair",  role:"Senior",         avatar:"PN", color:T.amber,   projects:2, utilization:65, expertise:["CA","NY","NJ"], status:"active"  },
  { id:6, name:"Marcus Lee",  role:"Staff",          avatar:"ML", color:"#E879F9", projects:3, utilization:82, expertise:["TX","AR","OK"], status:"active"  },
];

const STATE_DATA = [
  { state:"TX", nexus:"Physical+Economic", status:"Under Audit",    exposure:3100000, filings:"Monthly",   risk:"Critical" },
  { state:"CA", nexus:"Economic",          status:"Registered",     exposure:890000,  filings:"Monthly",   risk:"High"     },
  { state:"WY", nexus:"Physical",          status:"Under Audit",    exposure:7800000, filings:"Quarterly", risk:"Critical" },
  { state:"AR", nexus:"Physical",          status:"Refund Pending", exposure:670000,  filings:"Quarterly", risk:"Medium"   },
  { state:"NY", nexus:"Economic",          status:"Registered",     exposure:220000,  filings:"Monthly",   risk:"Low"      },
  { state:"LA", nexus:"Physical",          status:"Registered",     exposure:410000,  filings:"Monthly",   risk:"Medium"   },
  { state:"OK", nexus:"Physical+Economic", status:"Registered",     exposure:330000,  filings:"Monthly",   risk:"Medium"   },
  { state:"WA", nexus:"Economic",          status:"Registered",     exposure:175000,  filings:"Monthly",   risk:"Low"      },
];

const AUDIT_NOTICES = [
  { id:1, client:"BlueRidge Manufacturing", state:"TX", agency:"Texas Comptroller",   period:"2021",      type:"Full Audit",           exposure:3100000, deadline:"2024-02-10", status:"Active",    daysLeft:4  },
  { id:2, client:"Cascade Oil & Gas",       state:"WY", agency:"WY Dept of Revenue", period:"2018-2022", type:"Severance Audit",      exposure:7800000, deadline:"2024-03-01", status:"Active",    daysLeft:24 },
  { id:3, client:"Meridian Energy Corp",    state:"LA", agency:"LA Dept of Revenue", period:"2020-2021", type:"Sales Tax Desk Audit", exposure:410000,  deadline:"2024-04-15", status:"Responded", daysLeft:69 },
];

const REFUNDS = [
  { id:1, client:"Ozark Resources LLC",  state:"AR", type:"Severance Tax",   estimated:670000,  filed:670000,  recovered:0,      status:"Filed — Pending Approval", pct:0   },
  { id:2, client:"Meridian Energy Corp", state:"TX", type:"Sales & Use Tax", estimated:1120000, filed:980000,  recovered:340000, status:"Partial Recovery",         pct:35  },
  { id:3, client:"Meridian Energy Corp", state:"LA", type:"Sales Tax",       estimated:140000,  filed:140000,  recovered:140000, status:"Fully Recovered",          pct:100 },
];

const NAV_ITEMS = [
  { id:"dashboard", icon:"⬡", label:"Command Center"  },
  { id:"projects",  icon:"◈", label:"Projects"         },
  { id:"tasks",     icon:"◻", label:"Task Board"       },
  { id:"states",    icon:"◉", label:"State Tracker"    },
  { id:"audits",    icon:"⚑", label:"Audit Management" },
  { id:"refunds",   icon:"◆", label:"Refund Tracker"   },
  { id:"team",      icon:"◈", label:"Team & Workload"  },
  { id:"research",  icon:"⊕", label:"Research Hub"     },
  { id:"reports",   icon:"▤", label:"Reports"          },
  { id:"copilot",   icon:"✦", label:"Tax Copilot AI"   },
];

// ─── MODULE-LEVEL CONSTANTS (fixes #1 #2 #3 #4) ──────────────────────────────
const TASK_COLS = ["Planning","In Progress","Review Phase","Waiting for Client","Filed"];

const RESEARCH_TYPE_COLOR = {
  "Official Ruling":  T.emerald,
  "Internal Memo":    T.blue,
  "Research Note":    T.violet,
  "Taxability Matrix":T.amber,
  "State Guidance":   T.cyan,
};

const RESEARCH_ARTICLES = [
  { title:"TX Comptroller — Manufacturing Exemption Guidance 2023", state:"TX",    type:"Official Ruling",   date:"2023-11", tags:["Manufacturing","Exemption","SUT"]  },
  { title:"Wayfair Economic Nexus Thresholds — All 50 States",      state:"Multi", type:"Internal Memo",     date:"2024-01", tags:["Nexus","Economic","Multi-State"]   },
  { title:"WY Severance Tax — Oil & Gas Valuation Methods",         state:"WY",    type:"Research Note",     date:"2023-09", tags:["Severance","O&G","Valuation"]      },
  { title:"SaaS Taxability Matrix — NY, NJ, CT, PA, MA",            state:"Multi", type:"Taxability Matrix", date:"2024-01", tags:["SaaS","Digital","Taxability"]      },
  { title:"AR Severance Tax Refund Procedures — Rev Ruling 2022-04",state:"AR",    type:"Official Ruling",   date:"2022-04", tags:["Severance","Refund","AR"]          },
  { title:"CA Economic Nexus — Remote Seller Guidance Update",      state:"CA",    type:"State Guidance",    date:"2023-11", tags:["Nexus","CA","Remote Seller"]       },
];

const RESEARCH_FILTER_OPTIONS = [
  "All","Official Ruling","Internal Memo","Taxability Matrix","Research Note","State Guidance",
];

const REPORT_LIST = [
  { title:"State Exposure Summary",    desc:"Total exposure by state across all engagements",  icon:"◉", color:T.crimson },
  { title:"Team Utilization Report",   desc:"Billable hours, capacity, workload by role",       icon:"◈", color:T.blue    },
  { title:"Refund Recovery Dashboard", desc:"Pipeline, filed, recovered, and recovery rates",   icon:"◆", color:T.emerald },
  { title:"Audit Resolution Metrics",  desc:"Open audits, response times, resolution rates",    icon:"⚑", color:T.amber   },
  { title:"Project Profitability",     desc:"Revenue, write-offs, realization by engagement",   icon:"⬡", color:T.violet  },
  { title:"SLA Compliance Report",     desc:"Deadline adherence and turnaround analysis",       icon:"⏱", color:T.cyan    },
];

const COPILOT_RESPONSES = {
  nexus:   "Based on your current portfolio, **StellarNet Logistics** has the highest nexus risk. They have economic nexus in CA (>$500K threshold exceeded Q3 2023) with no current registration. Recommend immediate voluntary disclosure to minimize exposure (~$890K at risk).",
  audit:   "Your most time-critical audit is **BlueRidge TX** — deadline in **4 days**. The IDR Batch 3 response covers $3.1M in assessed tax. Key arguments: (1) manufacturing exemption on packaging equipment, (2) resale exemption documentation gaps fixable via retroactive certificates.",
  refund:  "Top refund opportunities:\n1. **Meridian Energy Corp TX** — $780K remaining unclaimed\n2. **Ozark Resources AR** — $670K filed, pending approval\n3. **Potential** — Cascade WY may have $400K+ in severance overpayments (2018-2019, pre-audit period)",
  risk:    "Portfolio risk summary:\n🔴 **Critical (3):** BlueRidge TX, Cascade WY, StellarNet CA\n🟡 **High (1):** Meridian Energy TX\n🟢 **Medium-Low (2):** Ozark AR, Pinnacle Retail\n\nRecommend escalating Cascade WY — $7.8M exposure with only 24 days to deadline.",
  default: "That's a great question. Based on your current engagement data, I'd recommend reviewing your state exposure matrix and ensuring all IDR deadlines are calendared. Would you like me to generate a risk-prioritized action list for this week?",
};

const QUICK_PROMPTS = [
  "Analyze my nexus risk exposure",
  "What's my most critical audit?",
  "Show refund opportunities",
  "Portfolio risk summary",
];

// ─── HELPERS ─────────────────────────────────────────────────────────────────
const fmt$ = (n) =>
  n >= 1000000 ? `$${(n/1000000).toFixed(1)}M` :
  n >= 1000    ? `$${(n/1000).toFixed(0)}K`    : `$${n}`;

const riskColor    = (r) => ({ Critical:T.crimson, High:T.amber, Medium:T.blue, Low:T.emerald }[r] || T.text2);
const priorityColor= (p) => ({ Critical:T.crimson, High:T.amber, Medium:T.blue, Low:T.emerald }[p] || T.text2);
const statusColor  = (s) => ({
  "In Progress":T.blue, "Review Phase":T.violet, "Escalated":T.crimson,
  "Waiting for Client":T.amber, "Filed":T.emerald, "Closed":T.text3,
  "Planning":T.cyan, "On Hold":T.text3, "Responded":T.emerald,
}[s] || T.text2);

// ─── GLOBAL STYLES ───────────────────────────────────────────────────────────
const GlobalStyles = () => (
  <style>{`
    *, *::before, *::after { box-sizing:border-box; margin:0; padding:0; }
    html, body { height:100%; background:${T.bg0}; color:${T.text0};
      font-family:-apple-system,'SF Pro Display','Inter',system-ui,sans-serif; overflow:hidden; }
    ::-webkit-scrollbar { width:4px; height:4px; }
    ::-webkit-scrollbar-track { background:transparent; }
    ::-webkit-scrollbar-thumb { background:${T.bg4}; border-radius:4px; }
    ::-webkit-scrollbar-thumb:hover { background:${T.text3}; }
    * { scrollbar-width:thin; scrollbar-color:${T.bg4} transparent; }
    @keyframes fadeUp  { from{opacity:0;transform:translateY(14px)} to{opacity:1;transform:translateY(0)} }
    @keyframes pulse   { 0%,100%{opacity:1} 50%{opacity:0.45} }
    @keyframes glow    { 0%,100%{box-shadow:0 0 12px ${T.blueGlow}} 50%{box-shadow:0 0 28px rgba(59,130,246,0.45)} }
    @keyframes countUp { from{opacity:0;transform:scale(0.85)} to{opacity:1;transform:scale(1)} }
    @keyframes shimmer { 0%{background-position:-200% 0} 100%{background-position:200% 0} }
    .fadeUp     { animation:fadeUp 0.38s ease forwards; }
    .hover-lift { transition:transform 0.2s ease, box-shadow 0.2s ease; }
    .hover-lift:hover { transform:translateY(-2px); box-shadow:0 12px 40px rgba(0,0,0,0.45); }
    .btn-primary { background:linear-gradient(135deg,${T.blue},${T.blueDim}); color:#fff; border:none;
      cursor:pointer; font-weight:600; letter-spacing:0.01em; transition:all 0.2s; font-family:inherit; }
    .btn-primary:hover { filter:brightness(1.15); transform:translateY(-1px); box-shadow:0 8px 24px ${T.blueGlow}; }
    .btn-ghost  { background:transparent; color:${T.text1}; border:1px solid ${T.border};
      cursor:pointer; transition:all 0.2s; font-family:inherit; }
    .btn-ghost:hover { border-color:${T.borderHover}; background:${T.glass}; color:${T.text0}; }
    .card       { background:${T.bg2}; border:1px solid ${T.border}; border-radius:14px; transition:border-color 0.2s; }
    .card:hover { border-color:${T.borderHover}; }
    .glass-card { background:rgba(22,27,38,0.72); backdrop-filter:blur(20px); border:1px solid ${T.glassBorder}; }
    .progress-bar  { height:4px; border-radius:99px; background:${T.bg4}; overflow:hidden; }
    .progress-fill { height:100%; border-radius:99px; transition:width 0.6s ease; }
    .tag { display:inline-flex; align-items:center; gap:4px; padding:2px 8px;
      border-radius:6px; font-size:11px; font-weight:600; letter-spacing:0.04em; }
    .nav-item { display:flex; align-items:center; gap:10px; padding:8px 12px; border-radius:10px;
      cursor:pointer; transition:all 0.15s; color:${T.text2}; font-size:13px; font-weight:500;
      border:none; background:transparent; width:100%; text-align:left; }
    .nav-item:hover  { background:${T.bg3}; color:${T.text0}; }
    .nav-item.active { background:linear-gradient(135deg,rgba(59,130,246,0.18),rgba(59,130,246,0.06));
      color:${T.blue}; border-left:2px solid ${T.blue}; }
    .metric-card { background:${T.bg2}; border:1px solid ${T.border}; border-radius:16px;
      padding:20px; position:relative; overflow:hidden; }
    input, textarea, select { background:${T.bg3}; border:1px solid ${T.border}; color:${T.text0};
      border-radius:8px; font-size:13px; outline:none; font-family:inherit; }
    input:focus, textarea:focus, select:focus { border-color:${T.blue}; box-shadow:0 0 0 3px ${T.blueGlow}; }
    .skeleton { background:linear-gradient(90deg,${T.bg3} 25%,${T.bg4} 50%,${T.bg3} 75%);
      background-size:200% 100%; animation:shimmer 1.5s infinite; border-radius:6px; }
    .tooltip { position:relative; }
    .tooltip:hover::after { content:attr(data-tip); position:absolute; bottom:calc(100% + 6px);
      left:50%; transform:translateX(-50%); background:${T.bg4}; color:${T.text0}; font-size:11px;
      padding:4px 8px; border-radius:6px; white-space:nowrap; pointer-events:none;
      z-index:9999; border:1px solid ${T.border}; }
  `}</style>
);

// ─── SHARED UI PRIMITIVES ────────────────────────────────────────────────────
const Badge = ({ label, color }) => (
  <span className="tag" style={{ background:`${color}18`, color, border:`1px solid ${color}30` }}>
    {label}
  </span>
);

const HealthBar = ({ value }) => {
  const color = value >= 80 ? T.emerald : value >= 50 ? T.amber : T.crimson;
  return (
    <div style={{ display:"flex", alignItems:"center", gap:8 }}>
      <div className="progress-bar" style={{ flex:1 }}>
        <div className="progress-fill"
          style={{ width:`${value}%`, background:`linear-gradient(90deg,${color},${color}88)` }} />
      </div>
      <span style={{ fontSize:11, fontWeight:700, color, minWidth:26, textAlign:"right" }}>
        {value}%
      </span>
    </div>
  );
};

const Avatar = ({ initials, color, size=28 }) => (
  <div style={{
    width:size, height:size, borderRadius:"50%",
    background:`linear-gradient(135deg,${color},${color}88)`,
    display:"flex", alignItems:"center", justifyContent:"center",
    fontSize:size*0.35, fontWeight:700, color:"#fff",
    flexShrink:0, border:`2px solid ${T.bg2}`,
  }}>{initials}</div>
);

const SectionHeader = ({ title, sub, action, onAction }) => (
  <div style={{ display:"flex", alignItems:"flex-end", justifyContent:"space-between", marginBottom:20 }}>
    <div>
      <h2 style={{ fontSize:20, fontWeight:700, color:T.text0, letterSpacing:"-0.02em" }}>{title}</h2>
      {sub && <p style={{ fontSize:13, color:T.text3, marginTop:2 }}>{sub}</p>}
    </div>
    {action && (
      <button className="btn-ghost"
        style={{ fontSize:12, padding:"6px 14px", borderRadius:8 }}
        onClick={onAction}>{action}</button>
    )}
  </div>
);

const MetricCard = ({ label, value, sub, color, icon, delay=0 }) => {
  const numVal = useMemo(() => (typeof value === "number" ? value : null), [value]);
  const [displayed, setDisplayed] = useState(0);
  useEffect(() => {
    if (numVal === null) return;
    let current = 0;
    const step = (numVal / 800) * 16;
    const timer = setInterval(() => {
      current = Math.min(current + step, numVal);
      setDisplayed(Math.round(current));
      if (current >= numVal) clearInterval(timer);
    }, 16);
    return () => clearInterval(timer);
  }, [numVal]);
  const displayValue = numVal !== null
    ? (label.includes("Exposure")||label.includes("Refund")||label.includes("Pipeline")||
       label.includes("Filed")||label.includes("Recovered")||label.includes("Audit Exposure")
       ? fmt$(displayed) : displayed)
    : value;
  return (
    <div className="metric-card hover-lift fadeUp"
      style={{ animationDelay:`${delay}ms`, borderTop:`2px solid ${color}22` }}>
      <div style={{ position:"absolute", top:0, right:0, width:80, height:80,
        borderRadius:"50%", background:color, filter:"blur(30px)", opacity:0.12 }} />
      <div style={{ display:"flex", justifyContent:"space-between",
        alignItems:"flex-start", marginBottom:12 }}>
        <div style={{ fontSize:11, color:T.text3, fontWeight:600,
          letterSpacing:"0.06em", textTransform:"uppercase" }}>{label}</div>
        <div style={{ fontSize:18, opacity:0.7 }}>{icon}</div>
      </div>
      <div style={{ fontSize:28, fontWeight:700, color:T.text0,
        letterSpacing:"-0.02em", marginBottom:4, animation:"countUp 0.5s ease" }}>
        {displayValue}
      </div>
      <div style={{ fontSize:12, color:T.text3 }}>{sub}</div>
    </div>
  );
};

const AlertBanner = ({ color, icon, badge, text, cta, onClick }) => (
  <div style={{ background:`${color}15`, border:`1px solid ${color}30`, borderRadius:10,
    padding:"10px 16px", display:"flex", alignItems:"center", gap:10, flex:1 }}>
    <span style={{ fontSize:18 }}>{icon}</span>
    <div>
      <div style={{ fontSize:11, color, fontWeight:700, letterSpacing:"0.06em" }}>{badge}</div>
      <div style={{ fontSize:12, color:T.text1 }}>{text}</div>
    </div>
    <button className="btn-ghost" onClick={onClick}
      style={{ marginLeft:"auto", fontSize:11, padding:"4px 10px",
        borderRadius:6, borderColor:`${color}30`, color }}>{cta}</button>
  </div>
);

// ─── COMMAND PALETTE ─────────────────────────────────────────────────────────
const CommandPalette = ({ open, onClose, onNavigate }) => {
  const [query, setQuery] = useState("");
  const inputRef = useRef();
  const commands = useMemo(() => [
    { label:"Command Center",              icon:"⬡",  action:() => onNavigate("dashboard") },
    { label:"All Projects",                icon:"◈",  action:() => onNavigate("projects")  },
    { label:"Task Board",                  icon:"◻",  action:() => onNavigate("tasks")     },
    { label:"State Tracker",               icon:"◉",  action:() => onNavigate("states")    },
    { label:"Audit Management",            icon:"⚑",  action:() => onNavigate("audits")    },
    { label:"Refund Tracker",              icon:"◆",  action:() => onNavigate("refunds")   },
    { label:"Team & Workload",             icon:"◈",  action:() => onNavigate("team")      },
    { label:"Research Hub",                icon:"⊕",  action:() => onNavigate("research")  },
    { label:"Reports",                     icon:"▤",  action:() => onNavigate("reports")   },
    { label:"Tax Copilot AI",              icon:"✦",  action:() => onNavigate("copilot")   },
    { label:"CA SUT audits",               icon:"🔍", action:() => onNavigate("states")    },
    { label:"Projects due this week",      icon:"🔍", action:() => onNavigate("projects")  },
    { label:"Critical risk projects",      icon:"🔍", action:() => onNavigate("projects")  },
    { label:"Refund opportunities >$500K", icon:"🔍", action:() => onNavigate("refunds")   },
  ], [onNavigate]);
  const filtered = useMemo(() =>
    query ? commands.filter(c => c.label.toLowerCase().includes(query.toLowerCase())) : commands,
  [query, commands]);
  useEffect(() => { if (open) { setQuery(""); inputRef.current?.focus(); } }, [open]);
  if (!open) return null;
  const handleKeyDown = (e) => {
    if (e.key === "Escape") onClose();
    if (e.key === "Enter" && filtered[0]) { filtered[0].action(); onClose(); }
  };
  return (
    <div onClick={onClose} style={{ position:"fixed", inset:0, background:"rgba(0,0,0,0.72)",
      zIndex:9999, display:"flex", alignItems:"flex-start", justifyContent:"center",
      paddingTop:"15vh", backdropFilter:"blur(8px)" }}>
      <div onClick={e => e.stopPropagation()} className="glass-card fadeUp" style={{
        width:"100%", maxWidth:580, borderRadius:16, overflow:"hidden",
        boxShadow:"0 40px 100px rgba(0,0,0,0.7)" }}>
        <div style={{ display:"flex", alignItems:"center", gap:12,
          padding:"14px 18px", borderBottom:`1px solid ${T.border}` }}>
          <span style={{ color:T.text3, fontSize:16 }}>⌘</span>
          <input ref={inputRef} value={query} onChange={e => setQuery(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Search projects, clients, states… or type a command"
            style={{ flex:1, background:"transparent", border:"none", fontSize:14,
              color:T.text0, padding:0 }} />
          <kbd style={{ background:T.bg4, padding:"2px 6px", borderRadius:4,
            fontSize:11, color:T.text3, border:`1px solid ${T.border}` }}>ESC</kbd>
        </div>
        <div style={{ maxHeight:380, overflowY:"auto", padding:8 }}>
          {filtered.length === 0
            ? <div style={{ padding:"24px", textAlign:"center", color:T.text3, fontSize:13 }}>
                No results found
              </div>
            : filtered.map((c, i) => (
              <div key={i} onClick={() => { c.action(); onClose(); }}
                style={{ display:"flex", alignItems:"center", gap:12, padding:"10px 12px",
                  borderRadius:8, cursor:"pointer", transition:"background 0.15s" }}
                onMouseEnter={e => e.currentTarget.style.background = T.bg3}
                onMouseLeave={e => e.currentTarget.style.background = "transparent"}>
                <span style={{ fontSize:14, width:20, textAlign:"center", color:T.text3 }}>{c.icon}</span>
                <span style={{ fontSize:13, color:T.text1 }}>{c.label}</span>
                {query && <span style={{ marginLeft:"auto", fontSize:11, color:T.text3 }}>↵ Enter</span>}
              </div>
            ))
          }
        </div>
        <div style={{ padding:"8px 18px", borderTop:`1px solid ${T.border}`,
          display:"flex", gap:16, alignItems:"center" }}>
          {[["↑↓","Navigate"],["↵","Select"],["ESC","Close"]].map(([k,v]) => (
            <div key={k} style={{ display:"flex", gap:6, alignItems:"center" }}>
              <kbd style={{ background:T.bg4, padding:"1px 6px", borderRadius:4,
                fontSize:10, color:T.text2, border:`1px solid ${T.border}` }}>{k}</kbd>
              <span style={{ fontSize:11, color:T.text3 }}>{v}</span>
            </div>
          ))}
          <div style={{ marginLeft:"auto", fontSize:11, color:T.text3 }}>TaxOps Elite</div>
        </div>
      </div>
    </div>
  );
};

// ─── SIDEBAR ─────────────────────────────────────────────────────────────────
const Sidebar = ({ active, onNav, collapsed, onToggle }) => (
  <aside style={{ width:collapsed?60:224, background:T.bg1,
    borderRight:`1px solid ${T.border}`, height:"100vh", display:"flex",
    flexDirection:"column", transition:"width 0.25s cubic-bezier(.4,0,.2,1)",
    flexShrink:0, overflow:"hidden" }}>
    <div style={{ padding:collapsed?"18px 12px":"18px 16px",
      borderBottom:`1px solid ${T.border}`, display:"flex",
      alignItems:"center", gap:10, minHeight:61 }}>
      <div style={{ width:32, height:32, borderRadius:8, flexShrink:0,
        background:`linear-gradient(135deg,${T.blue},${T.violet})`,
        display:"flex", alignItems:"center", justifyContent:"center",
        fontSize:14, boxShadow:`0 4px 14px ${T.blueGlow}`,
        animation:"glow 3s ease-in-out infinite" }}>⬡</div>
      {!collapsed && (
        <div>
          <div style={{ fontSize:13, fontWeight:700, letterSpacing:"0.02em", color:T.text0 }}>
            TaxOps Elite
          </div>
          <div style={{ fontSize:10, color:T.text3, letterSpacing:"0.08em" }}>INDIRECT TAX OS</div>
        </div>
      )}
      <button onClick={onToggle} style={{ marginLeft:"auto", background:"transparent",
        border:"none", color:T.text3, cursor:"pointer", fontSize:14,
        flexShrink:0, padding:2 }}>{collapsed?"›":"‹"}</button>
    </div>
    <div style={{ flex:1, overflowY:"auto", padding:"10px 8px" }}>
      {!collapsed && (
        <div style={{ fontSize:10, fontWeight:700, letterSpacing:"0.1em",
          color:T.text3, padding:"8px 8px 4px", textTransform:"uppercase" }}>Workspace</div>
      )}
      <div style={{ display:"flex", flexDirection:"column", gap:1 }}>
        {NAV_ITEMS.map(item => (
          <button key={item.id} onClick={() => onNav(item.id)}
            title={collapsed ? item.label : ""}
            className={`nav-item${active===item.id?" active":""}`}
            style={{ borderLeft:active===item.id?`2px solid ${T.blue}`:"2px solid transparent",
              justifyContent:collapsed?"center":"flex-start" }}>
            <span style={{ fontSize:15, flexShrink:0 }}>{item.icon}</span>
            {!collapsed && <span>{item.label}</span>}
          </button>
        ))}
      </div>
    </div>
    <div style={{ padding:collapsed?"12px 8px":"12px 12px",
      borderTop:`1px solid ${T.border}` }}>
      <div style={{ display:"flex", alignItems:"center", gap:10 }}>
        <div style={{ width:30, height:30, borderRadius:"50%", flexShrink:0,
          background:`linear-gradient(135deg,${T.violet},${T.blue})`,
          display:"flex", alignItems:"center", justifyContent:"center",
          fontSize:11, fontWeight:700 }}>YA</div>
        {!collapsed && (
          <div>
            <div style={{ fontSize:12, fontWeight:600, color:T.text0 }}>Your Account</div>
            <div style={{ fontSize:10, color:T.text3 }}>Senior Manager</div>
          </div>
        )}
      </div>
    </div>
  </aside>
);

// ─── TOPBAR ──────────────────────────────────────────────────────────────────
const NotifButton = ({ icon, tip, badge }) => {
  const [hov, setHov] = useState(false);
  return (
    <div className="tooltip" data-tip={tip} style={{ position:"relative" }}>
      <button onMouseEnter={() => setHov(true)} onMouseLeave={() => setHov(false)}
        style={{ width:34, height:34, borderRadius:8, cursor:"pointer", fontSize:15,
          background:hov?T.bg4:T.bg3, color:hov?T.text0:T.text2,
          border:`1px solid ${T.border}`, transition:"all 0.15s",
          display:"flex", alignItems:"center", justifyContent:"center" }}>{icon}</button>
      {badge && (
        <div style={{ position:"absolute", top:3, right:3, width:14, height:14,
          borderRadius:"50%", background:T.crimson, fontSize:9, fontWeight:700,
          color:"#fff", display:"flex", alignItems:"center", justifyContent:"center",
          border:`2px solid ${T.bg1}` }}>{badge}</div>
      )}
    </div>
  );
};

const TopBar = ({ onCommand, activeView }) => {
  const [hovered, setHovered] = useState(false);
  const label = NAV_ITEMS.find(n => n.id === activeView)?.label || "TaxOps Elite";
  return (
    <div style={{ height:52, background:T.bg1, borderBottom:`1px solid ${T.border}`,
      display:"flex", alignItems:"center", paddingInline:24, gap:16, flexShrink:0 }}>
      <div style={{ fontSize:13, fontWeight:600, color:T.text0, flex:1 }}>{label}</div>
      <button onClick={onCommand}
        onMouseEnter={() => setHovered(true)} onMouseLeave={() => setHovered(false)}
        style={{ display:"flex", alignItems:"center", gap:8, background:T.bg3,
          border:`1px solid ${hovered?T.borderHover:T.border}`, borderRadius:8,
          padding:"6px 12px", cursor:"pointer",
          color:hovered?T.text1:T.text3, fontSize:12, transition:"all 0.15s" }}>
        <span>⌘</span>
        <span>Search or jump to...</span>
        <kbd style={{ background:T.bg4, padding:"1px 5px", borderRadius:4,
          fontSize:10, border:`1px solid ${T.border}`, marginLeft:4 }}>⌘K</kbd>
      </button>
      <div style={{ display:"flex", gap:6, alignItems:"center" }}>
        <NotifButton icon="🔔" tip="Notifications" badge={5} />
        <NotifButton icon="⚙" tip="Settings" />
        <div style={{ width:34, height:34, borderRadius:"50%",
          background:`linear-gradient(135deg,${T.violet},${T.blue})`,
          display:"flex", alignItems:"center", justifyContent:"center",
          fontSize:12, fontWeight:700, cursor:"pointer" }}>YA</div>
      </div>
    </div>
  );
};

// ─── DASHBOARD VIEW ──────────────────────────────────────────────────────────
const DashboardView = ({ onNavigate }) => {
  const totalExposure = useMemo(() => PROJECTS.reduce((s,p) => s+p.exposure, 0), []);
  const totalRefund   = useMemo(() => PROJECTS.reduce((s,p) => s+p.refund,   0), []);
  const criticalCount = useMemo(() => PROJECTS.filter(p => p.risk==="Critical").length, []);
  const overdueAudits = useMemo(() => AUDIT_NOTICES.filter(a => a.daysLeft<10).length, []);
  return (
    <div style={{ padding:"28px 32px", overflowY:"auto", height:"100%",
      display:"flex", flexDirection:"column", gap:28 }}>
      <div className="fadeUp">
        <div style={{ display:"flex", alignItems:"center", justifyContent:"space-between" }}>
          <div>
            <h1 style={{ fontSize:24, fontWeight:700, letterSpacing:"-0.03em", color:T.text0 }}>
              Command Center{" "}
              <span style={{ fontSize:13, fontWeight:400, color:T.text3 }}>— Good morning</span>
            </h1>
            <p style={{ fontSize:13, color:T.text3, marginTop:3 }}>
              Indirect Tax Operations · {new Date().toLocaleDateString("en-US",
                { weekday:"long", month:"long", day:"numeric" })}
            </p>
          </div>
          <div style={{ display:"flex", gap:10 }}>
            <button className="btn-ghost"
              style={{ fontSize:12, padding:"8px 16px", borderRadius:10 }}
              onClick={() => onNavigate("projects")}>⊕ New Project</button>
            <button className="btn-primary"
              style={{ fontSize:12, padding:"8px 16px", borderRadius:10 }}
              onClick={() => onNavigate("tasks")}>⬡ Quick Add</button>
          </div>
        </div>
        <div style={{ display:"flex", gap:8, marginTop:14 }}>
          <AlertBanner color={T.crimson} icon="⚑" badge="URGENT"
            text={<>BlueRidge TX Audit deadline in <strong style={{color:T.crimson}}>4 days</strong></>}
            cta="View →" onClick={() => onNavigate("audits")} />
          <AlertBanner color={T.amber} icon="◉" badge="OVERLOADED"
            text={<>Alex Torres at <strong style={{color:T.amber}}>97% utilization</strong> — rebalance needed</>}
            cta="Rebalance →" onClick={() => onNavigate("team")} />
        </div>
      </div>
      <div style={{ display:"grid", gridTemplateColumns:"repeat(5,1fr)", gap:14 }}>
        <MetricCard label="Active Projects" value={PROJECTS.length} sub="2 critical risk"    color={T.blue}    icon="◈" delay={0}   />
        <MetricCard label="Total Exposure"  value={totalExposure}   sub="across 8 states"    color={T.crimson} icon="⚠" delay={60}  />
        <MetricCard label="Refund Pipeline" value={totalRefund}     sub="~35% recovered"     color={T.emerald} icon="◆" delay={120} />
        <MetricCard label="Critical Risk"   value={criticalCount}   sub="require escalation" color={T.amber}   icon="⚑" delay={180} />
        <MetricCard label="Audit Deadlines" value={overdueAudits}   sub="due within 10 days" color={T.violet}  icon="⏱" delay={240} />
      </div>
      <div style={{ display:"grid", gridTemplateColumns:"1.6fr 1fr", gap:18 }}>
        <div>
          <SectionHeader title="Active Engagements"
            sub={`${PROJECTS.filter(p=>p.status!=="Closed").length} live projects`}
            action="View All" onAction={() => onNavigate("projects")} />
          <div style={{ display:"flex", flexDirection:"column", gap:10 }}>
            {PROJECTS.slice(0,4).map((p,i) => (
              <div key={p.id} className="card hover-lift fadeUp"
                style={{ padding:"16px 18px", animationDelay:`${i*55}ms`, cursor:"pointer" }}>
                <div style={{ display:"flex", alignItems:"flex-start",
                  justifyContent:"space-between", marginBottom:10 }}>
                  <div style={{ flex:1, minWidth:0 }}>
                    <div style={{ display:"flex", alignItems:"center", gap:8, marginBottom:3 }}>
                      <span style={{ fontSize:12, fontWeight:700, color:T.text0,
                        overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" }}>
                        {p.client}
                      </span>
                      <Badge label={p.priority} color={priorityColor(p.priority)} />
                      <Badge label={`${p.risk} Risk`} color={riskColor(p.risk)} />
                    </div>
                    <div style={{ fontSize:11, color:T.text3, overflow:"hidden",
                      textOverflow:"ellipsis", whiteSpace:"nowrap" }}>{p.engagement}</div>
                  </div>
                  <div style={{ textAlign:"right", flexShrink:0, marginLeft:12 }}>
                    <div style={{ fontSize:13, fontWeight:700, color:T.text0 }}>{fmt$(p.exposure)}</div>
                    <div style={{ fontSize:10, color:T.text3 }}>exposure</div>
                  </div>
                </div>
                <div style={{ display:"flex", alignItems:"center",
                  justifyContent:"space-between", marginBottom:10 }}>
                  <div style={{ display:"flex", gap:4, flexWrap:"wrap" }}>
                    {p.states.slice(0,4).map(s => (
                      <span key={s} className="tag"
                        style={{ background:T.bg4, color:T.text2,
                          border:`1px solid ${T.border}`, fontSize:10 }}>{s}</span>
                    ))}
                    {p.states.length>4 && (
                      <span className="tag"
                        style={{ background:T.bg4, color:T.text3,
                          border:`1px solid ${T.border}`, fontSize:10 }}>
                        +{p.states.length-4}
                      </span>
                    )}
                  </div>
                  <span style={{ fontSize:11, color:statusColor(p.status), fontWeight:600 }}>
                    ● {p.status}
                  </span>
                </div>
                <HealthBar value={p.health} />
              </div>
            ))}
          </div>
        </div>
        <div style={{ display:"flex", flexDirection:"column", gap:18 }}>
          <div>
            <SectionHeader title="Audit Deadlines"
              action="View All" onAction={() => onNavigate("audits")} />
            <div style={{ display:"flex", flexDirection:"column", gap:8 }}>
              {AUDIT_NOTICES.map((a,i) => (
                <div key={a.id} className="card fadeUp"
                  style={{ padding:"12px 14px", animationDelay:`${i*50}ms`,
                    borderLeft:`3px solid ${a.daysLeft<10?T.crimson:a.daysLeft<30?T.amber:T.emerald}` }}>
                  <div style={{ display:"flex", justifyContent:"space-between", marginBottom:4 }}>
                    <span style={{ fontSize:12, fontWeight:600, color:T.text0 }}>{a.client}</span>
                    <span style={{ fontSize:11, fontWeight:700,
                      color:a.daysLeft<10?T.crimson:T.amber }}>{a.daysLeft}d left</span>
                  </div>
                  <div style={{ fontSize:11, color:T.text3 }}>
                    {a.state} · {a.type} · {fmt$(a.exposure)}
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div>
            <SectionHeader title="Team Utilization"
              action="View All" onAction={() => onNavigate("team")} />
            <div style={{ display:"flex", flexDirection:"column", gap:8 }}>
              {TEAM.slice(0,5).map((m,i) => (
                <div key={m.id} className="fadeUp" style={{ animationDelay:`${i*40}ms` }}>
                  <div style={{ display:"flex", alignItems:"center", gap:10, marginBottom:4 }}>
                    <Avatar initials={m.avatar} color={m.color} size={26} />
                    <span style={{ fontSize:12, color:T.text1, flex:1 }}>{m.name}</span>
                    <span style={{ fontSize:11, fontWeight:700,
                      color:m.utilization>90?T.crimson:m.utilization>75?T.amber:T.emerald }}>
                      {m.utilization}%
                    </span>
                  </div>
                  <div className="progress-bar">
                    <div className="progress-fill" style={{
                      width:`${m.utilization}%`,
                      background:m.utilization>90?T.crimson:m.utilization>75?T.amber:T.emerald }} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// ─── PROJECTS VIEW ───────────────────────────────────────────────────────────
const ProjectsView = () => {
  const [filterVal, setFilterVal] = useState("All");
  const [searchVal, setSearchVal] = useState("");
  const FILTERS = ["All","Critical","In Progress","Review Phase","Escalated","Waiting for Client"];
  const visible = useMemo(() => PROJECTS.filter(p => {
    const matchF = filterVal==="All"||p.status===filterVal||p.priority===filterVal||p.risk===filterVal;
    const q = searchVal.toLowerCase();
    const matchS = !q||p.client.toLowerCase().includes(q)||p.engagement.toLowerCase().includes(q);
    return matchF && matchS;
  }), [filterVal, searchVal]);
  return (
    <div style={{ padding:"28px 32px", overflowY:"auto", height:"100%",
      display:"flex", flexDirection:"column", gap:20 }}>
      <SectionHeader title="Projects"
        sub={`${PROJECTS.length} total engagements · ${PROJECTS.filter(p=>p.risk==="Critical").length} critical`}
        action="⊕ New Project" />
      <div style={{ display:"flex", gap:10, alignItems:"center", flexWrap:"wrap" }}>
        <input value={searchVal} onChange={e => setSearchVal(e.target.value)}
          placeholder="Search clients, engagements..."
          style={{ padding:"8px 14px", width:280, height:36 }} />
        <div style={{ display:"flex", gap:6, flexWrap:"wrap" }}>
          {FILTERS.map(f => (
            <button key={f} onClick={() => setFilterVal(f)}
              style={{
                padding:"6px 12px", borderRadius:8, fontSize:12, fontWeight:600,
                cursor:"pointer", transition:"all 0.15s", fontFamily:"inherit",
                background: filterVal===f ? T.blue : "transparent",
                color:       filterVal===f ? "#fff"  : T.text2,
                border:      filterVal===f ? `1px solid ${T.blue}` : `1px solid ${T.border}`,
              }}>{f}</button>
          ))}
        </div>
      </div>
      <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(360px,1fr))", gap:14 }}>
        {visible.map((p,i) => (
          <div key={p.id} className="card hover-lift fadeUp"
            style={{ padding:"20px", cursor:"pointer",
              animationDelay:`${i*40}ms`, borderTop:`2px solid ${riskColor(p.risk)}22` }}>
            <div style={{ display:"flex", justifyContent:"space-between",
              alignItems:"flex-start", marginBottom:14 }}>
              <div>
                <div style={{ fontSize:14, fontWeight:700, color:T.text0, marginBottom:3 }}>
                  {p.client}
                </div>
                <div style={{ fontSize:11, color:T.text3, lineHeight:1.4, maxWidth:220 }}>
                  {p.engagement}
                </div>
              </div>
              <div style={{ textAlign:"right", flexShrink:0, marginLeft:12 }}>
                <div style={{ fontSize:16, fontWeight:700, color:T.text0 }}>{fmt$(p.exposure)}</div>
                <div style={{ fontSize:10, color:T.text3 }}>exposure</div>
                {p.refund>0 && (
                  <div style={{ fontSize:12, fontWeight:600, color:T.emerald }}>
                    {fmt$(p.refund)} refund
                  </div>
                )}
              </div>
            </div>
            <div style={{ display:"flex", gap:6, flexWrap:"wrap", marginBottom:12 }}>
              <Badge label={p.type}     color={T.blue}                    />
              <Badge label={p.tax}      color={T.violet}                  />
              <Badge label={p.priority} color={priorityColor(p.priority)} />
            </div>
            <div style={{ display:"flex", gap:4, flexWrap:"wrap", marginBottom:14 }}>
              {p.states.map(s => (
                <span key={s} className="tag"
                  style={{ background:T.bg4, color:T.text2,
                    border:`1px solid ${T.border}`, fontSize:10 }}>{s}</span>
              ))}
            </div>
            <div style={{ display:"flex", justifyContent:"space-between", marginBottom:10 }}>
              <span style={{ fontSize:11, color:statusColor(p.status), fontWeight:600 }}>
                ● {p.status}
              </span>
              <span style={{ fontSize:11, color:T.text3 }}>Due {p.due}</span>
            </div>
            <HealthBar value={p.health} />
            <div style={{ display:"flex", justifyContent:"space-between",
              marginTop:12, paddingTop:12, borderTop:`1px solid ${T.border}` }}>
              <div style={{ display:"flex", gap:14 }}>
                <span style={{ fontSize:11, color:T.text3 }}>👤 {p.manager}</span>
                <span style={{ fontSize:11, color:T.text3 }}>{p.tasks} tasks</span>
                <span style={{ fontSize:11, color:p.open>10?T.amber:T.text3 }}>
                  {p.open} open
                </span>
              </div>
              <span style={{ fontSize:11, color:T.text3 }}>{p.billingType}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── TASKS VIEW ──────────────────────────────────────────────────────────────
const TasksView = () => {
  const allTasksByCol = useMemo(() => ({
    "Planning":           TASKS.filter(t => t.status==="Planning"),
    "In Progress":        TASKS.filter(t => t.status==="In Progress"),
    "Review Phase":       TASKS.filter(t => t.status==="Review Phase"),
    "Waiting for Client": TASKS.filter(t => t.status==="Waiting for Client"),
    "Filed":              [],
  }), []);
  return (
    <div style={{ padding:"28px 32px", height:"100%", display:"flex",
      flexDirection:"column", gap:20, overflow:"hidden" }}>
      <SectionHeader title="Task Board"
        sub={`${TASKS.length} active tasks · Kanban view`}
        action="⊕ Add Task" />
      <div style={{ display:"flex", gap:12, overflowX:"auto", flex:1, paddingBottom:8 }}>
        {TASK_COLS.map(col => (
          <div key={col} style={{ minWidth:280, display:"flex", flexDirection:"column" }}>
            <div style={{ padding:"10px 12px", background:T.bg2,
              borderRadius:"12px 12px 0 0",
              border:`1px solid ${T.border}`, borderBottom:"none",
              display:"flex", justifyContent:"space-between", alignItems:"center" }}>
              <span style={{ fontSize:12, fontWeight:700,
                color:T.text1, letterSpacing:"0.02em" }}>{col}</span>
              <span style={{ fontSize:11, background:T.bg4, color:T.text3,
                padding:"2px 8px", borderRadius:20 }}>
                {allTasksByCol[col]?.length || 0}
              </span>
            </div>
            <div style={{ flex:1, background:`${T.bg2}44`,
              border:`1px solid ${T.border}`, borderTop:"none",
              borderRadius:"0 0 12px 12px", padding:8,
              display:"flex", flexDirection:"column", gap:8,
              minHeight:400, overflowY:"auto" }}>
              {(allTasksByCol[col]||[]).map((t,i) => (
                <div key={t.id} className="card hover-lift fadeUp"
                  style={{ padding:"14px", cursor:"grab", animationDelay:`${i*50}ms` }}>
                  <div style={{ display:"flex", justifyContent:"space-between",
                    alignItems:"flex-start", marginBottom:8 }}>
                    <span style={{ fontSize:12, fontWeight:600, color:T.text0,
                      lineHeight:1.4, flex:1, paddingRight:8 }}>{t.title}</span>
                    <Badge label={t.priority} color={priorityColor(t.priority)} />
                  </div>
                  <div style={{ fontSize:11, color:T.text3, marginBottom:10 }}>
                    {t.project}
                  </div>
                  <div style={{ display:"flex", justifyContent:"space-between",
                    alignItems:"center", marginBottom:10 }}>
                    <div style={{ display:"flex", alignItems:"center", gap:6 }}>
                      <Avatar
                        initials={t.assignee.split(" ").map(n=>n[0]).join("")}
                        color={TEAM.find(m=>m.name===t.assignee)?.color||T.blue}
                        size={22} />
                      <span style={{ fontSize:11, color:T.text2 }}>
                        {t.assignee.split(" ")[0]}
                      </span>
                    </div>
                    <span style={{ fontSize:11, color:T.text3 }}>Due {t.due}</span>
                  </div>
                  <div>
                    <div style={{ display:"flex", justifyContent:"space-between", marginBottom:4 }}>
                      <span style={{ fontSize:10, color:T.text3 }}>
                        {t.hours}h / {t.estimate}h logged
                      </span>
                      <span style={{ fontSize:10, color:T.text3 }}>
                        {t.estimate>0 ? Math.round((t.hours/t.estimate)*100) : 0}%
                      </span>
                    </div>
                    <div className="progress-bar">
                      <div className="progress-fill" style={{
                        width: t.estimate>0
                          ? `${Math.min((t.hours/t.estimate)*100,100)}%`
                          : "0%",
                        background:T.blue }} />
                    </div>
                  </div>
                </div>
              ))}
              {(allTasksByCol[col]||[]).length===0 && (
                <div style={{ flex:1, display:"flex", alignItems:"center",
                  justifyContent:"center", color:T.text3, fontSize:12,
                  flexDirection:"column", gap:8, padding:24, opacity:0.6 }}>
                  <span style={{ fontSize:24 }}>◻</span>
                  <span>No tasks</span>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── STATE TRACKER VIEW ──────────────────────────────────────────────────────
const StatesView = () => {
  const underAudit = useMemo(() => STATE_DATA.filter(s=>s.status.includes("Audit")).length,  []);
  const refundPend = useMemo(() => STATE_DATA.filter(s=>s.status.includes("Refund")).length, []);
  const totalExp   = useMemo(() => STATE_DATA.reduce((a,s)=>a+s.exposure, 0),                []);
  return (
    <div style={{ padding:"28px 32px", overflowY:"auto", height:"100%",
      display:"flex", flexDirection:"column", gap:20 }}>
      <SectionHeader title="State Tracker"
        sub="Nexus footprint · Filing obligations · Audit exposure across all jurisdictions"
        action="⊕ Add State" />
      <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:12, marginBottom:4 }}>
        <MetricCard label="States Tracked" value={STATE_DATA.length} sub="in portfolio"      color={T.blue}    icon="◉" delay={0}   />
        <MetricCard label="Under Audit"     value={underAudit}        sub="active reviews"    color={T.crimson} icon="⚑" delay={50}  />
        <MetricCard label="Refund Pending"  value={refundPend}        sub="awaiting state"    color={T.emerald} icon="◆" delay={100} />
        <MetricCard label="Total Exposure"  value={totalExp}          sub="across all states" color={T.amber}   icon="⚠" delay={150} />
      </div>
      <div className="card" style={{ overflow:"hidden" }}>
        <table style={{ width:"100%", borderCollapse:"collapse" }}>
          <thead>
            <tr style={{ borderBottom:`1px solid ${T.border}`, background:T.bg3 }}>
              {["State","Nexus Type","Status","Exposure","Audit Status","Filing Freq","Risk"].map(h => (
                <th key={h} style={{ padding:"12px 16px", textAlign:"left", fontSize:11,
                  fontWeight:700, color:T.text3,
                  letterSpacing:"0.06em", textTransform:"uppercase" }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {STATE_DATA.map((s,i) => (
              <tr key={s.state} className="fadeUp"
                style={{ borderBottom:`1px solid ${T.border}`,
                  animationDelay:`${i*40}ms`, transition:"background 0.15s", cursor:"pointer" }}
                onMouseEnter={e => e.currentTarget.style.background=T.bg3}
                onMouseLeave={e => e.currentTarget.style.background="transparent"}>
                <td style={{ padding:"14px 16px" }}>
                  <div style={{ width:32, height:22, borderRadius:4, background:T.bg4,
                    border:`1px solid ${T.border}`, display:"flex", alignItems:"center",
                    justifyContent:"center", fontSize:11, fontWeight:800,
                    color:T.text0, letterSpacing:"0.04em" }}>{s.state}</div>
                </td>
                <td style={{ padding:"14px 16px" }}>
                  <Badge label={s.nexus} color={s.nexus.includes("+") ? T.violet : T.blue} />
                </td>
                <td style={{ padding:"14px 16px" }}>
                  <span style={{ fontSize:12, color:statusColor(s.status), fontWeight:600 }}>
                    ● {s.status}
                  </span>
                </td>
                <td style={{ padding:"14px 16px" }}>
                  <span style={{ fontSize:13, fontWeight:700, color:T.text0 }}>
                    {fmt$(s.exposure)}
                  </span>
                </td>
                <td style={{ padding:"14px 16px" }}>
                  <Badge label={s.status}
                    color={s.status.includes("Audit") ? T.crimson
                         : s.status.includes("Refund") ? T.emerald : T.text3} />
                </td>
                <td style={{ padding:"14px 16px" }}>
                  <span style={{ fontSize:12, color:T.text2 }}>{s.filings}</span>
                </td>
                <td style={{ padding:"14px 16px" }}>
                  <Badge label={s.risk} color={riskColor(s.risk)} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

// ─── AUDIT MANAGEMENT VIEW ───────────────────────────────────────────────────
const AuditsView = () => {
  const totalAuditExp = useMemo(() => AUDIT_NOTICES.reduce((a,n)=>a+n.exposure, 0), []);
  const urgent        = useMemo(() => AUDIT_NOTICES.filter(a=>a.daysLeft<10).length,            []);
  const responded     = useMemo(() => AUDIT_NOTICES.filter(a=>a.status==="Responded").length,   []);
  return (
    <div style={{ padding:"28px 32px", overflowY:"auto", height:"100%",
      display:"flex", flexDirection:"column", gap:20 }}>
      <SectionHeader title="Audit Management"
        sub="Active audit notices · IDR tracking · Response deadlines · Resolution status"
        action="⊕ New Audit Notice" />
      <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:12 }}>
        <MetricCard label="Active Audits"        value={AUDIT_NOTICES.length} sub="across 2 states"    color={T.crimson} icon="⚑" delay={0}   />
        <MetricCard label="Total Audit Exposure" value={totalAuditExp}        sub="combined estimate"  color={T.amber}   icon="⚠" delay={50}  />
        <MetricCard label="Urgent Deadlines"     value={urgent}               sub="due within 10 days" color={T.crimson} icon="⏱" delay={100} />
        <MetricCard label="Responded"            value={responded}            sub="IDRs submitted"     color={T.emerald} icon="✓" delay={150} />
      </div>
      <div style={{ display:"flex", flexDirection:"column", gap:14 }}>
        {AUDIT_NOTICES.map((a,i) => (
          <div key={a.id} className="card hover-lift fadeUp"
            style={{ padding:"22px 24px", animationDelay:`${i*60}ms`,
              borderLeft:`4px solid ${a.daysLeft<10?T.crimson:a.daysLeft<30?T.amber:T.emerald}` }}>
            <div style={{ display:"flex", alignItems:"flex-start",
              justifyContent:"space-between", marginBottom:14 }}>
              <div>
                <div style={{ display:"flex", alignItems:"center", gap:10, marginBottom:4 }}>
                  <span style={{ fontSize:15, fontWeight:700, color:T.text0 }}>{a.client}</span>
                  <Badge label={a.type} color={T.blue} />
                  <Badge label={a.status}
                    color={a.status==="Active" ? T.crimson
                         : a.status==="Responded" ? T.emerald : T.amber} />
                </div>
                <div style={{ fontSize:12, color:T.text3 }}>
                  {a.agency} · Audit Period: {a.period}
                </div>
              </div>
              <div style={{ textAlign:"right" }}>
                <div style={{ fontSize:20, fontWeight:700, color:T.text0 }}>{fmt$(a.exposure)}</div>
                <div style={{ fontSize:11, color:T.text3 }}>exposure estimate</div>
              </div>
            </div>
            <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:16,
              padding:"14px 16px", background:T.bg3, borderRadius:10, marginBottom:14 }}>
              {[
                { label:"State",          value: a.state },
                { label:"Deadline",       value: a.deadline },
                { label:"Days Remaining", value: (
                  <span style={{ color:a.daysLeft<10?T.crimson:a.daysLeft<30?T.amber:T.emerald,
                    fontWeight:700 }}>{a.daysLeft} days</span>
                )},
                { label:"Status", value: (
                  <span style={{ color:statusColor(a.status) }}>● {a.status}</span>
                )},
              ].map(({ label, value }) => (
                <div key={label}>
                  <div style={{ fontSize:10, color:T.text3, fontWeight:700,
                    letterSpacing:"0.06em", textTransform:"uppercase", marginBottom:4 }}>
                    {label}
                  </div>
                  <div style={{ fontSize:13, fontWeight:600, color:T.text0 }}>{value}</div>
                </div>
              ))}
            </div>
            <div style={{ display:"flex", gap:8 }}>
              <button className="btn-primary"
                style={{ fontSize:12, padding:"8px 16px", borderRadius:8 }}>
                View IDR Log
              </button>
              <button className="btn-ghost"
                style={{ fontSize:12, padding:"8px 16px", borderRadius:8 }}>
                Upload Document
              </button>
              <button className="btn-ghost"
                style={{ fontSize:12, padding:"8px 16px", borderRadius:8 }}>
                Draft Response
              </button>
              {a.daysLeft<10 && (
                <button className="btn-ghost"
                  style={{ fontSize:12, padding:"8px 16px", borderRadius:8,
                    borderColor:`${T.crimson}40`, color:T.crimson, marginLeft:"auto" }}>
                  ⚑ Escalate
                </button>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── REFUND TRACKER VIEW ─────────────────────────────────────────────────────
const RefundsView = () => {
  const totalEst   = useMemo(() => REFUNDS.reduce((a,r)=>a+r.estimated, 0), []);
  const totalFiled = useMemo(() => REFUNDS.reduce((a,r)=>a+r.filed,     0), []);
  const totalRec   = useMemo(() => REFUNDS.reduce((a,r)=>a+r.recovered,  0), []);
  return (
    <div style={{ padding:"28px 32px", overflowY:"auto", height:"100%",
      display:"flex", flexDirection:"column", gap:20 }}>
      <SectionHeader title="Refund Tracker"
        sub="Recovery pipeline · Filing status · Estimated vs. actual savings"
        action="⊕ New Refund Claim" />
      <div style={{ display:"grid", gridTemplateColumns:"repeat(4,1fr)", gap:12 }}>
        <MetricCard label="Refund Pipeline" value={totalEst}   sub="total estimated"     color={T.emerald} icon="◆" delay={0}   />
        <MetricCard label="Filed Claims"    value={totalFiled} sub="submitted to states"  color={T.blue}    icon="◈" delay={50}  />
        <MetricCard label="Recovered"       value={totalRec}   sub="cash in hand"         color={T.cyan}    icon="✓" delay={100} />
        <MetricCard label="Recovery Rate"   value="26%"        sub="overall effectiveness" color={T.violet}  icon="⬡" delay={150} />
      </div>
      <div style={{ display:"flex", flexDirection:"column", gap:12 }}>
        {REFUNDS.map((r,i) => (
          <div key={r.id} className="card hover-lift fadeUp"
            style={{ padding:"22px 24px", animationDelay:`${i*60}ms` }}>
            <div style={{ display:"flex", alignItems:"flex-start",
              justifyContent:"space-between", marginBottom:16 }}>
              <div>
                <div style={{ display:"flex", gap:8, alignItems:"center", marginBottom:4 }}>
                  <span style={{ fontSize:14, fontWeight:700, color:T.text0 }}>{r.client}</span>
                  <Badge label={r.state} color={T.blue}   />
                  <Badge label={r.type}  color={T.violet} />
                </div>
                <div style={{ fontSize:12, color:T.text3 }}>
                  Status:{" "}
                  <span style={{ color:r.pct===100?T.emerald:r.pct>0?T.amber:T.blue,
                    fontWeight:600 }}>{r.status}</span>
                </div>
              </div>
              <div style={{ display:"flex", gap:28, textAlign:"right" }}>
                {[
                  { label:"Estimated", value:fmt$(r.estimated), color:T.text0   },
                  { label:"Filed",     value:fmt$(r.filed),     color:T.blue    },
                  { label:"Recovered", value:fmt$(r.recovered), color:T.emerald },
                ].map(({ label, value, color }) => (
                  <div key={label}>
                    <div style={{ fontSize:10, color:T.text3, letterSpacing:"0.06em",
                      textTransform:"uppercase", marginBottom:2 }}>{label}</div>
                    <div style={{ fontSize:16, fontWeight:700, color }}>{value}</div>
                  </div>
                ))}
              </div>
            </div>
            <div style={{ marginBottom:8 }}>
              <div style={{ display:"flex", justifyContent:"space-between", marginBottom:6 }}>
                <span style={{ fontSize:12, color:T.text3 }}>Recovery Progress</span>
                <span style={{ fontSize:12, fontWeight:700,
                  color:r.pct===100?T.emerald:r.pct>0?T.amber:T.blue }}>{r.pct}%</span>
              </div>
              <div className="progress-bar" style={{ height:8 }}>
                <div className="progress-fill" style={{
                  width:`${r.pct}%`,
                  background: r.pct===100
                    ? `linear-gradient(90deg,${T.emerald},${T.cyan})`
                    : r.pct>0
                      ? `linear-gradient(90deg,${T.amber},${T.blue})`
                      : T.blue }} />
              </div>
            </div>
            <div style={{ display:"flex", gap:8, marginTop:14 }}>
              <button className="btn-ghost"
                style={{ fontSize:12, padding:"7px 14px", borderRadius:8 }}>
                View Filing
              </button>
              <button className="btn-ghost"
                style={{ fontSize:12, padding:"7px 14px", borderRadius:8 }}>
                Upload Correspondence
              </button>
              {r.pct<100 && (
                <button className="btn-primary"
                  style={{ fontSize:12, padding:"7px 14px", borderRadius:8, marginLeft:"auto" }}>
                  Follow Up →
                </button>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// ─── TEAM VIEW ───────────────────────────────────────────────────────────────
const TeamView = () => (
  <div style={{ padding:"28px 32px", overflowY:"auto", height:"100%",
    display:"flex", flexDirection:"column", gap:20 }}>
    <SectionHeader title="Team & Workload"
      sub="Utilization · Assignment matrix · Capacity planning"
      action="⊕ Add Team Member" />
    <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:14 }}>
      {TEAM.map((m,i) => (
        <div key={m.id} className="card hover-lift fadeUp"
          style={{ padding:"20px", animationDelay:`${i*50}ms`,
            borderTop:`2px solid ${m.color}33` }}>
          <div style={{ display:"flex", alignItems:"center", gap:12, marginBottom:16 }}>
            <Avatar initials={m.avatar} color={m.color} size={44} />
            <div>
              <div style={{ fontSize:14, fontWeight:700, color:T.text0 }}>{m.name}</div>
              <div style={{ fontSize:11, color:T.text3 }}>{m.role}</div>
              <div style={{ marginTop:4 }}>
                <span className="tag" style={{
                  background: m.status==="at-risk" ? `${T.crimson}18` : `${T.emerald}18`,
                  color:       m.status==="at-risk" ? T.crimson         : T.emerald,
                  border:`1px solid ${m.status==="at-risk" ? T.crimson : T.emerald}30`,
                  fontSize:10 }}>
                  {m.status==="at-risk" ? "⚠ Overloaded" : "● Active"}
                </span>
              </div>
            </div>
            <div style={{ marginLeft:"auto", textAlign:"right" }}>
              <div style={{ fontSize:22, fontWeight:700,
                color:m.utilization>90?T.crimson:m.utilization>75?T.amber:T.emerald }}>
                {m.utilization}%
              </div>
              <div style={{ fontSize:10, color:T.text3 }}>utilization</div>
            </div>
          </div>
          <div className="progress-bar" style={{ marginBottom:14, height:6 }}>
            <div className="progress-fill" style={{
              width:`${m.utilization}%`,
              background:m.utilization>90?T.crimson:m.utilization>75?T.amber:T.emerald }} />
          </div>
          <div style={{ fontSize:12, color:T.text2, marginBottom:12 }}>
            {m.projects} active projects
          </div>
          <div>
            <div style={{ fontSize:10, color:T.text3, marginBottom:6,
              textTransform:"uppercase", letterSpacing:"0.06em" }}>State Expertise</div>
            <div style={{ display:"flex", gap:4, flexWrap:"wrap" }}>
              {m.expertise.map(s => (
                <span key={s} className="tag"
                  style={{ background:T.bg4, color:T.text2,
                    border:`1px solid ${T.border}`, fontSize:10 }}>{s}</span>
              ))}
            </div>
          </div>
          <div style={{ marginTop:14, paddingTop:14,
            borderTop:`1px solid ${T.border}`, display:"flex", gap:8 }}>
            <button className="btn-ghost"
              style={{ flex:1, fontSize:11, padding:"6px", borderRadius:7 }}>
              View Profile
            </button>
            <button className="btn-ghost"
              style={{ flex:1, fontSize:11, padding:"6px", borderRadius:7 }}>
              Assign Task
            </button>
          </div>
        </div>
      ))}
    </div>
  </div>
);

// ─── RESEARCH HUB VIEW ───────────────────────────────────────────────────────
const ResearchView = () => {
  const [activeFilter, setActiveFilter] = useState("All");
  const [searchQ,      setSearchQ]      = useState("");
  const visible = useMemo(() =>
    RESEARCH_ARTICLES.filter(a => {
      const matchType = activeFilter==="All" || a.type===activeFilter;
      const q = searchQ.toLowerCase();
      const matchQ = !q
        || a.title.toLowerCase().includes(q)
        || a.state.toLowerCase().includes(q)
        || a.tags.some(t => t.toLowerCase().includes(q));
      return matchType && matchQ;
    }),
  [activeFilter, searchQ]);
  return (
    <div style={{ padding:"28px 32px", overflowY:"auto", height:"100%",
      display:"flex", flexDirection:"column", gap:20 }}>
      <SectionHeader title="Research Hub"
        sub="Rulings · Internal memos · Taxability matrices · State guidance"
        action="⊕ Add Research" />
      <div style={{ display:"flex", gap:10, flexWrap:"wrap", alignItems:"center" }}>
        <input value={searchQ} onChange={e => setSearchQ(e.target.value)}
          placeholder="Search research, rulings, states..."
          style={{ padding:"8px 14px", width:300, height:36 }} />
        {RESEARCH_FILTER_OPTIONS.map(f => (
          <button key={f} onClick={() => setActiveFilter(f)}
            style={{ fontSize:12, padding:"6px 12px", borderRadius:8,
              cursor:"pointer", transition:"all 0.15s", fontFamily:"inherit",
              background: activeFilter===f ? T.blue : "transparent",
              color:       activeFilter===f ? "#fff"  : T.text2,
              border:      activeFilter===f
                ? `1px solid ${T.blue}` : `1px solid ${T.border}` }}>{f}</button>
        ))}
      </div>
      <div style={{ display:"grid", gridTemplateColumns:"repeat(2,1fr)", gap:12 }}>
        {visible.map((a,i) => (
          <div key={i} className="card hover-lift fadeUp"
            style={{ padding:"18px 20px", cursor:"pointer",
              animationDelay:`${i*40}ms`,
              borderLeft:`3px solid ${RESEARCH_TYPE_COLOR[a.type]||T.blue}` }}>
            <div style={{ display:"flex", justifyContent:"space-between",
              alignItems:"flex-start", marginBottom:8 }}>
              <span style={{ fontSize:13, fontWeight:600, color:T.text0,
                lineHeight:1.4, flex:1, paddingRight:12 }}>{a.title}</span>
              <span className="tag" style={{
                background:`${RESEARCH_TYPE_COLOR[a.type]||T.blue}15`,
                color: RESEARCH_TYPE_COLOR[a.type]||T.blue,
                border:`1px solid ${RESEARCH_TYPE_COLOR[a.type]||T.blue}30`,
                flexShrink:0, fontSize:10 }}>{a.type}</span>
            </div>
            <div style={{ fontSize:11, color:T.text3, marginBottom:10 }}>
              {a.state} · Updated {a.date}
            </div>
            <div style={{ display:"flex", gap:4, flexWrap:"wrap" }}>
              {a.tags.map(tag => (
                <span key={tag} className="tag"
                  style={{ background:T.bg4, color:T.text2,
                    border:`1px solid ${T.border}`, fontSize:10 }}>{tag}</span>
              ))}
            </div>
          </div>
        ))}
        {visible.length===0 && (
          <div style={{ gridColumn:"1/-1", textAlign:"center",
            padding:"48px", color:T.text3, fontSize:13 }}>
            No research articles match your filter.
          </div>
        )}
      </div>
    </div>
  );
};

// ─── REPORTS VIEW ────────────────────────────────────────────────────────────
const ReportsView = () => (
  <div style={{ padding:"28px 32px", overflowY:"auto", height:"100%",
    display:"flex", flexDirection:"column", gap:20 }}>
    <SectionHeader title="Executive Reports"
      sub="Export-ready analytics · PDF · Excel · CSV" />
    <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:14 }}>
      {REPORT_LIST.map((r,i) => (
        <div key={i} className="card hover-lift fadeUp"
          style={{ padding:"24px", cursor:"pointer",
            animationDelay:`${i*50}ms`, borderTop:`2px solid ${r.color}33` }}>
          <div style={{ fontSize:28, marginBottom:14, opacity:0.85 }}>{r.icon}</div>
          <div style={{ fontSize:14, fontWeight:700, color:T.text0, marginBottom:6 }}>
            {r.title}
          </div>
          <div style={{ fontSize:12, color:T.text3, marginBottom:18, lineHeight:1.55 }}>
            {r.desc}
          </div>
          <div style={{ display:"flex", gap:6 }}>
            {["PDF","Excel","CSV"].map(fmt => (
              <button key={fmt} className="btn-ghost"
                style={{ fontSize:11, padding:"5px 10px", borderRadius:6, flex:1 }}>
                {fmt}
              </button>
            ))}
          </div>
        </div>
      ))}
    </div>
  </div>
);

// ─── TAX COPILOT AI VIEW ─────────────────────────────────────────────────────
const CopilotView = () => {
  const [messages,  setMessages]  = useState([{
    role:"assistant",
    text:"Hello! I'm **Tax Copilot**, your AI assistant for indirect tax operations. I can help with:\n\n• Risk analysis across your project portfolio\n• Nexus exposure assessment\n• Audit strategy recommendations\n• Refund opportunity identification\n• Deadline prioritization\n• Draft IDR responses\n\nWhat would you like to explore today?",
  }]);
  const [input,    setInput]    = useState("");
  const [thinking, setThinking] = useState(false);
  const bottomRef = useRef();
  const inputRef  = useRef("");
  useEffect(() => { inputRef.current = input; }, [input]);
  const send = useCallback((override) => {
    const userMsg = (override ?? inputRef.current).trim();
    if (!userMsg) return;
    setMessages(prev => [...prev, { role:"user", text:userMsg }]);
    setInput("");
    setThinking(true);
    setTimeout(() => {
      const key = Object.keys(COPILOT_RESPONSES).find(k =>
        userMsg.toLowerCase().includes(k)
      ) || "default";
      setMessages(prev => [...prev, { role:"assistant", text:COPILOT_RESPONSES[key] }]);
      setThinking(false);
    }, 1200);
  }, []);
  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior:"smooth" });
  }, [messages, thinking]);
  const renderText = (text) =>
    text.split("\n").map((line,i) => {
      const html = line.replace(
        /\*\*(.*?)\*\*/g,
        (_,b) => `<strong style="color:${T.text0}">${b}</strong>`
      );
      return (
        <div key={i}
          style={{ marginBottom:line===""?8:0, minHeight:line===""?8:undefined }}
          dangerouslySetInnerHTML={{ __html:html||" " }} />
      );
    });
  return (
    <div style={{ padding:"28px 32px", height:"100%", display:"flex",
      flexDirection:"column", overflow:"hidden" }}>
      <div style={{ marginBottom:20, flexShrink:0 }}>
        <div style={{ display:"flex", alignItems:"center", gap:12 }}>
          <div style={{ width:40, height:40, borderRadius:12, flexShrink:0,
            background:`linear-gradient(135deg,${T.violet},${T.blue})`,
            display:"flex", alignItems:"center", justifyContent:"center",
            fontSize:18, boxShadow:`0 4px 20px ${T.violetGlow}`,
            animation:"glow 3s ease-in-out infinite" }}>✦</div>
          <div>
            <h2 style={{ fontSize:18, fontWeight:700, color:T.text0 }}>Tax Copilot</h2>
            <p style={{ fontSize:12, color:T.text3 }}>
              AI-powered indirect tax intelligence · Powered by GPT-4
            </p>
          </div>
          <div style={{ marginLeft:"auto" }}>
            <span className="tag" style={{ background:`${T.emerald}15`, color:T.emerald,
              border:`1px solid ${T.emerald}30`, animation:"pulse 2s infinite" }}>
              ● Online
            </span>
          </div>
        </div>
      </div>
      <div style={{ flex:1, overflowY:"auto", display:"flex",
        flexDirection:"column", gap:16, paddingBottom:8 }}>
        {messages.map((m,i) => (
          <div key={i} className="fadeUp" style={{ display:"flex", gap:12,
            justifyContent:m.role==="user"?"flex-end":"flex-start" }}>
            {m.role==="assistant" && (
              <div style={{ width:30, height:30, borderRadius:8, flexShrink:0, marginTop:2,
                background:`linear-gradient(135deg,${T.violet},${T.blue})`,
                display:"flex", alignItems:"center", justifyContent:"center",
                fontSize:12 }}>✦</div>
            )}
            <div style={{ maxWidth:"75%",
              background:m.role==="user"
                ? `linear-gradient(135deg,${T.blue},${T.blueDim})` : T.bg2,
              border:`1px solid ${m.role==="user"?T.blue:T.border}`,
              borderRadius:m.role==="user"?"16px 16px 4px 16px":"4px 16px 16px 16px",
              padding:"14px 16px", fontSize:13, lineHeight:1.65, color:T.text1 }}>
              {renderText(m.text)}
            </div>
            {m.role==="user" && (
              <div style={{ width:30, height:30, borderRadius:"50%", flexShrink:0,
                background:`linear-gradient(135deg,${T.violet},${T.blue})`,
                display:"flex", alignItems:"center", justifyContent:"center",
                fontSize:11, fontWeight:700 }}>YA</div>
            )}
          </div>
        ))}
        {thinking && (
          <div style={{ display:"flex", gap:12 }}>
            <div style={{ width:30, height:30, borderRadius:8,
              background:`linear-gradient(135deg,${T.violet},${T.blue})`,
              display:"flex", alignItems:"center", justifyContent:"center",
              fontSize:12 }}>✦</div>
            <div style={{ background:T.bg2, border:`1px solid ${T.border}`,
              borderRadius:"4px 16px 16px 16px", padding:"14px 18px" }}>
              <div style={{ display:"flex", gap:6, alignItems:"center" }}>
                {[0,1,2].map(d => (
                  <div key={d} style={{ width:6, height:6, borderRadius:"50%",
                    background:T.blue, animation:"pulse 1.2s ease-in-out infinite",
                    animationDelay:`${d*0.2}s` }} />
                ))}
              </div>
            </div>
          </div>
        )}
        <div ref={bottomRef} />
      </div>
      <div style={{ paddingTop:12, flexShrink:0, display:"flex",
        flexDirection:"column", gap:10 }}>
        <div style={{ display:"flex", gap:6, flexWrap:"wrap" }}>
          {QUICK_PROMPTS.map(p => (
            <button key={p} className="btn-ghost"
              style={{ fontSize:11, padding:"5px 12px", borderRadius:20 }}
              onClick={() => send(p)}>{p}</button>
          ))}
        </div>
        <div style={{ display:"flex", gap:8 }}>
          <input value={input} onChange={e => setInput(e.target.value)}
            onKeyDown={e => e.key==="Enter" && send()}
            placeholder="Ask Tax Copilot anything — audits, nexus, refunds, risks..."
            style={{ flex:1, padding:"12px 16px", borderRadius:12, fontSize:13 }} />
          <button className="btn-primary" onClick={() => send()}
            style={{ padding:"12px 20px", borderRadius:12, fontSize:13, flexShrink:0 }}>
            Send ↵
          </button>
        </div>
      </div>
    </div>
  );
};

// ─── VIEW MAP (lazy render — fix #7) ─────────────────────────────────────────
const VIEW_MAP = {
  dashboard: (nav) => <DashboardView onNavigate={nav} />,
  projects:  ()    => <ProjectsView  />,
  tasks:     ()    => <TasksView     />,
  states:    ()    => <StatesView    />,
  audits:    ()    => <AuditsView    />,
  refunds:   ()    => <RefundsView   />,
  team:      ()    => <TeamView      />,
  research:  ()    => <ResearchView  />,
  reports:   ()    => <ReportsView   />,
  copilot:   ()    => <CopilotView   />,
};

// ─── ROOT APP ────────────────────────────────────────────────────────────────
export default function App() {
  const [activeView,       setActiveView]       = useState("dashboard");
  const [cmdOpen,          setCmdOpen]          = useState(false);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

  const navigate = useCallback((view) => {
    setActiveView(view);
    setCmdOpen(false);
  }, []);

  useEffect(() => {
    const handler = (e) => {
      if ((e.metaKey||e.ctrlKey) && e.key==="k") {
        e.preventDefault();
        setCmdOpen(o => !o);
      }
      if (e.key==="Escape") setCmdOpen(false);
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, []);

  const currentView = useMemo(
    () => (VIEW_MAP[activeView] ?? VIEW_MAP.dashboard)(navigate),
    [activeView, navigate]
  );

  return (
    <>
      <GlobalStyles />
      <CommandPalette
        open={cmdOpen}
        onClose={() => setCmdOpen(false)}
        onNavigate={navigate} />
      <div style={{ position:"fixed", inset:0, pointerEvents:"none", zIndex:0,
        background:`
          radial-gradient(ellipse 80% 50% at 20% 0%,  rgba(59,130,246,0.05) 0%, transparent 60%),
          radial-gradient(ellipse 60% 40% at 80% 100%, rgba(139,92,246,0.04) 0%, transparent 60%)
        ` }} />
      <div style={{ display:"flex", height:"100vh", position:"relative", zIndex:1 }}>
        <Sidebar
          active={activeView}
          onNav={navigate}
          collapsed={sidebarCollapsed}
          onToggle={() => setSidebarCollapsed(c => !c)} />
        <div style={{ flex:1, display:"flex", flexDirection:"column",
          overflow:"hidden", background:T.bg0 }}>
          <TopBar onCommand={() => setCmdOpen(true)} activeView={activeView} />
          <main style={{ flex:1, overflow:"hidden" }}>
            {currentView}
          </main>
        </div>
      </div>
      <button className="btn-primary" title="Quick Add (⌘K)"
        onClick={() => setCmdOpen(true)}
        style={{ position:"fixed", bottom:28, right:28, width:52, height:52,
          borderRadius:"50%", fontSize:22, display:"flex", alignItems:"center",
          justifyContent:"center",
          boxShadow:`0 8px 32px ${T.blueGlow}, 0 4px 16px rgba(0,0,0,0.5)`,
          zIndex:100, border:"none", animation:"glow 3s ease-in-out infinite" }}>⊕</button>
    </>
  );
}



